import Bot from "../models/bot.model.js";
import User from "../models/user.model.js";

export const Message=async(req,res)=>{
    try{
        const {text}=req.body;
        if(!text?.trim){
            return res.status(400).json({error:"Text connot be empty"});
        }

        const user=await User.create({
            sender:"user",
        })

    

        //data for train bot
        const botResponses={
            
  "intents": [
    {
      "tag": "greeting",
      "patterns": [
        "hello",
        "hi",
        "hey",
        "good morning",
        "good evening",
        "hi there",
        "hello bot",
        "hey assistant",
        "is anyone there",
        "yo",
        "hi buddy",
        "hey buddy",
        "good day",
        "hi what's up",
        "hey what's new",
        "hi how are you",
        "greetings",
        "hello friend",
        "hey pal",
        "hi assistant",
        "hello assistant",
        "hey service",
        "hi service",
        "hello shop",
        "hello ecommerce bot",
        "hey shopping bot",
        "hi chatbot",
        "hello chatbot",
        "yo chatbot",
        "hi dude",
        "hey dude",
        "hola",
        "hi bot",
        "hey there bot",
        "hello support",
        "hello support team",
        "hi support bot",
        "hey support bot",
        "hi can you help",
        "hello can you help",
        "hi i need help",
        "hey i need help",
        "hello i need assistance",
        "hi i need support",
        "hey you",
        "hi you",
        "hello anyone",
        "hello anyone here",
        "hi is someone here",
        "hello i am here",
        "hello how's it going",
        "hey how's it going",
        "hi how is everything",
        "hello how is everything",
        "hi there how are you doing",
        "hello hope you're there",
        "hi hope you can help",
        "hello nice to meet you",
        "hey nice to meet you",
        "hi nice meeting you",
        "hello good morning bot",
        "hi good evening bot",
        "hello good afternoon",
        "hey good afternoon",
        "hi hope your day is good",
        "hello happy to chat",
        "yo hey bot",
        "hello hello",
        "hi hi",
        "hey hey",
        "hi shop bot",
        "hello cart bot",
        "hola bot",
        "hi ecom bot",
        "hi amazon bot",
        "hi flipkart bot",
        "hello service assistant",
        "hello customer bot",
        "hey customer assistant",
        "hi order bot",
        "hello seller bot",
        "hi shopping partner",
        "hello buy bot",
        "hi sale bot",
        "hey store bot",
        "hello store assistant",
        "hi store support",
        "hey checkout bot",
        "hello checkout assistant",
        "hi online store bot",
        "hey online store",
        "hello market bot",
        "hi market assistant",
        "hello shopping assistant",
        "hi shopping helper",
        "hello virtual assistant",
        "hi virtual helper"
      ],
      "responses": [
        "Hello! How can I help you today?",
        "Hi there! What can I do for you?",
        "Hey! How may I assist with your shopping?"
      ]
    },

    {
      "tag": "order_status",
      "patterns": [
        "where is my order",
        "track my order",
        "track order 123",
        "order status please",
        "check order status",
        "what happened to my delivery",
        "my package is late",
        "when will my order arrive",
        "I want to know my order location",
        "track parcel",
        "show me my order details",
        "order not received yet",
        "my delivery is delayed",
        "status of my purchase",
        "track order for me",
        "can you track my package",
        "order tracking help",
        "delivery update please",
        "any update on my order",
        "check delivery",
        "order not delivered",
        "my order is missing",
        "I haven't received my item",
        "package delayed",
        "tell me delivery date",
        "status check",
        "track package 459",
        "need delivery information",
        "is my order shipped",
        "has my order been dispatched",
        "order location",
        "where is my parcel now",
        "track courier",
        "courier update",
        "shipment status",
        "shipment help",
        "update my delivery",
        "order tracking request",
        "where’s my shipment",
        "delivery information",
        "give me order update",
        "delivery check",
        "help track my order",
        "is my parcel out for delivery",
        "order dispatched?",
        "did my package ship",
        "shipment update please",
        "is my order coming today",
        "will my order come today",
        "expected delivery time",
        "expected delivery date",
        "order confirmation status",
        "have you shipped my order",
        "check my order now",
        "I want delivery details",
        "package tracking needed",
        "lost package maybe",
        "order lost?",
        "help me find my order",
        "delivery still pending",
        "pending order update",
        "shipping update",
        "can you tell me order status",
        "order tracking number please",
        "track using order ID",
        "order ID 892 check",
        "shipment number check",
        "delivery ETA",
        "ETA for my order",
        "arrival time for my package",
        "delivery pending status",
        "I need tracking ID",
        "provide tracking info",
        "I don't see order update",
        "order stuck",
        "package stuck",
        "why order delayed",
        "delivery running late",
        "can you check parcel status",
        "can you track my shipment",
        "status for my order",
        "delivery tracking",
        "package tracking help",
        "shipment tracking help",
        "order progress",
        "shipment details",
        "package information",
        "order update right now",
        "tell me status",
        "check my order id",
        "delivery check please",
        "please track my order",
        "find my parcel",
        "order location help",
        "shipment location help",
        "order ID status check",
        "order tracking assistance",
        "delivery support needed",
        "track my product"
      ],
      "responses": [
        "Sure! Please share your order ID.",
        "I'd be happy to check your order. What is your order number?",
        "Please provide your order ID so I can track it."
      ]
    },

    {
      "tag": "refund_policy",
      "patterns": [
        "what is the refund policy",
        "can I get a refund",
        "refund rules",
        "do you accept returns",
        "how do I return a product",
        "return and refund help",
        "tell me your refund process",
        "how long refund takes",
        "refund eligibility",
        "how do refunds work",
        "can I return my order",
        "return deadline",
        "money back guarantee",
        "refund terms",
        "I want my money back",
        "where is my refund",
        "refund not received",
        "refund time",
        "refund status",
        "return instructions",
        "return window",
        "return period",
        "refund period",
        "product return help",
        "return policy please",
        "tell me return rules",
        "return process explain",
        "refund request",
        "how do I claim refund",
        "refund assistance",
        "refund time frame",
        "refund processing time",
        "can I return this item",
        "return pickup rules",
        "return shipping charges",
        "reverse pickup details",
        "returning a damaged product",
        "I received a wrong item",
        "wrong product return",
        "defective item refund",
        "defective product return",
        "return without box",
        "return without bill",
        "refund without receipt",
        "refund without invoice",
        "policy on refunds",
        "refundable items list",
        "non refundable items",
        "return charges",
        "is return free",
        "return shipping cost",
        "refund procedure",
        "refund guarantee policy",
        "will I get full refund",
        "partial refund rule",
        "refund for damaged item",
        "do you have returns",
        "return my order",
        "where to request refund",
        "how to apply for return",
        "I want to return something",
        "can you guide refund process",
        "refund guidelines",
        "what's your return process",
        "refund instructions",
        "refund period length",
        "return policy help",
        "return rules explain",
        "return and replacement",
        "return within how many days",
        "refund within how many days",
        "refund after return",
        "refund after cancellation",
        "can I cancel order and refund",
        "refund on cancellation",
        "cancellation refund time",
        "how long cancellation refund takes",
        "refund availability",
        "money back rules",
        "refund terms and conditions",
        "please explain refund process",
        "I want to know refund details",
        "refund workflow",
        "refund processing rules",
        "refund for returns",
        "refund for cancellation",
        "refund for defective return",
        "refund no received help",
        "follow up refund",
        "refund tracking",
        "refund waiting help",
        "refund problem",
        "return condition",
        "conditions for refund",
        "requirements for return",
        "approve refund",
        "reject refund reason",
        "refund customer support",
        "help me with refund"
      ],
      "responses": [
        "You can apply for a return/refund within 7 days of delivery.",
        "Refunds are initiated after we receive and verify the returned item.",
        "Please share your order ID to check your refund status."
      ]
    },

    {
      "tag": "product_details",
      "patterns": [
        "tell me about this product",
        "product details please",
        "what is this item",
        "explain product",
        "what does this product do",
        "product features",
        "product description",
        "what are the specifications",
        "show me specs",
        "specification details please",
        "what is the material",
        "product material",
        "available colors",
        "available sizes",
        "show size details",
        "product color options",
        "what is the warranty",
        "does it have warranty",
        "product guarantee",
        "what is the model number",
        "is this durable",
        "is the quality good",
        "product weight",
        "how heavy is this product",
        "product dimensions",
        "height width details",
        "product measurement",
        "is this waterproof",
        "is this washable",
        "can I wash this",
        "is it original",
        "is it brand new",
        "is this genuine product",
        "product authenticity",
        "is it available in red",
        "is it available in blue",
        "what is the stock",
        "is it in stock",
        "stock details",
        "is it sold out",
        "product availability",
        "show features",
        "does it come with charger",
        "does it include battery",
        "does it include cable",
        "is assembly required",
        "does it require installation",
        "is installation free",
        "free installation",
        "how to use this product",
        "usage instructions",
        "product manual",
        "is manual included",
        "product quality review",
        "material type",
        "product made in",
        "origin of product",
        "manufacturing country",
        "brand name",
        "which brand is this",
        "product brand details",
        "does it have variants",
        "product variants",
        "does it have accessories",
        "what’s inside the box",
        "box contents",
        "what does it include",
        "unboxing details",
        "product lifespan",
        "how long it lasts",
        "is it energy efficient",
        "is it eco friendly",
        "product certifications",
        "is it safe",
        "safety instructions",
        "is it kid friendly",
        "is it pet friendly",
        "product comparison",
        "compare with other",
        "is it best seller",
        "is it trending",
        "top features",
        "highlight features",
        "key specifications",
        "what makes this special",
        "is this new launch",
        "is this latest version",
        "product upgrade details",
        "is it compatible",
        "compatibility information",
        "product use cases",
        "where can I use this",
        "recommended usage",
        "how long warranty",
        "warranty details please"
      ],
      "responses": [
        "Here are the product details...",
        "This product includes multiple features. What specific detail would you like?",
        "Sure! Which specification would you like to know?"
      ]
    },

    {
      "tag": "cancel_order",
      "patterns": [
        "I want to cancel my order",
        "cancel my order",
        "order cancellation",
        "cancel order now",
        "stop my order",
        "can you cancel the order",
        "how to cancel my order",
        "cancel placed order",
        "cancel order 123",
        "please cancel this",
        "I purchased by mistake",
        "wrong order placed",
        "ordered wrong item",
        "want to cancel delivery",
        "how do I stop shipment",
        "cancel shipping",
        "cancel delivery",
        "cancel before shipping",
        "cancel request",
        "I need cancellation",
        "cancel urgently",
        "order cancellation help",
        "help cancel my order",
        "cancelled item support",
        "I want refund cancel order",
        "mistaken order cancellation",
        "accidentally ordered",
        "cancel before dispatch",
        "cancel before packaging",
        "cancel before delivery",
        "cancel this product",
        "remove item from order",
        "delete my order",
        "can you stop the shipment",
        "is cancellation allowed",
        "cancellation period",
        "is cancellation possible",
        "want to reverse the order",
        "reverse order request",
        "stop sending order",
        "halt shipment",
        "halt delivery",
        "cancel my product",
        "I need to cancel urgently",
        "change order to cancel",
        "request order cancellation",
        "send cancellation request",
        "submit cancel request",
        "order stopped?",
        "please stop my order",
        "cancel it please",
        "cancel my purchase",
        "I want to undo the purchase",
        "reverse my order",
        "I changed my mind",
        "want to return and cancel",
        "I don't need it now",
        "don’t ship this",
        "don’t deliver this",
        "cancel as soon as possible",
        "stop processing my order",
        "do not ship",
        "do not deliver",
        "cancelation support",
        "cancelation department",
        "cancel right now",
        "cancel today",
        "maybe cancel",
        "please cancel fast",
        "cancelation error",
        "cancelation help needed",
        "cancel order status",
        "I want to stop order",
        "canceling product",
        "cancel service",
        "cancel request now",
        "stop purchase",
        "undo purchase",
        "undo this order",
        "stop item",
        "halt the product",
        "halt the package",
        "halt the delivery",
        "I don’t want it anymore",
        "cancel my booking",
        "cancel my item",
        "I want cancellation details",
        "can you help with cancellation",
        "cancel order and refund",
        "how long to cancel order",
        "is my order cancelable",
        "can I still cancel",
        "cancel after placing",
        "cancel after ordering",
        "cancel after confirmation",
        "how to apply cancelation",
        "cancel this ID"
      ],
      "responses": [
        "Sure! Please provide your order ID to cancel.",
        "I can help you cancel your order. What is your order number?",
        "Cancellation request received. Share the order ID please."
      ]
    },

    {
      "tag": "payment_issues",
      "patterns": [
        "payment failed",
        "payment not going through",
        "I can't pay",
        "payment error",
        "transaction failed",
        "my payment stuck",
        "payment pending",
        "money deducted but order not placed",
        "amount deducted twice",
        "double payment",
        "charged twice",
        "payment gateway error",
        "can't checkout",
        "checkout issue",
        "card not working",
        "UPI failed",
        "my UPI not working",
        "Netbanking failing",
        "credit card declined",
        "debit card declined",
        "card rejected",
        "payment verification failed",
        "can't complete payment",
        "payment unsuccessful",
        "transaction not processed",
        "I need help with payment",
        "payment support",
        "why payment failed",
        "why money deducted",
        "money deducted but no order",
        "refund for failed payment",
        "where is my deducted money",
        "pending transaction",
        "does failed payment refund automatically",
        "can you help with transaction",
        "payment retry issue",
        "cannot retry payment",
        "payment stuck in loading",
        "UPI timeout",
        "payment timeout",
        "bank server down?",
        "is there payment issue now",
        "payment gateway slow",
        "failed at checkout",
        "unable to pay",
        "can't place order due to payment",
        "I want to change payment method",
        "alternate payment method",
        "UPI alternatives",
        "netbanking alternative",
        "wallet payment issue",
        "wallet not working",
        "amazon pay not working",
        "GPay failed",
        "PhonePe failed",
        "Paytm failed",
        "payment processing too long",
        "money deducted no confirmation",
        "no order confirmation",
        "order failed payment success",
        "order failed still charged",
        "my bank deducted money",
        "transaction error",
        "gateway failed",
        "payment declined help",
        "payment charges issue",
        "payment blocked",
        "blocked payment",
        "why is payment blocked",
        "payment fraud alert",
        "verify payment method",
        "add card help",
        "card linking issue",
        "card expired",
        "card limit exceeded",
        "insufficient balance",
        "bank rejected my payment",
        "bank issue payment",
        "UPI limit exceeded",
        "wallet balance low",
        "cannot use card",
        "unable to use UPI",
        "unable to use wallet",
        "bank server issue?",
        "is payment available",
        "payment hota nahi hai",
        "checkout me issue",
        "transaction me problem",
        "payment process band hai?",
        "payment accept nahi ho raha",
        "money gone no order",
        "payment hogaya order nahi mila",
        "please check my payment issue",
        "solve my payment problem",
        "payment se related doubt",
        "I need payment assistance"
      ],
      "responses": [
        "Sorry about the payment inconvenience. Could you share your transaction ID?",
        "Payments sometimes fail due to bank issues. Please share order/transaction ID.",
        "If money was deducted, it will be refunded automatically in 3–5 days."
      ]
    },

    {
      "tag": "offers_and_discounts",
      "patterns": [
        "any offers available",
        "discounts available?",
        "give me a coupon",
        "apply coupon code",
        "show me offers",
        "is there any sale",
        "sale today?",
        "today's discount?",
        "any cashback?",
        "festival offer?",
        "weekend sale?",
        "is there promo code",
        "best deals please",
        "cheap price available?",
        "lowest price offer?",
        "upcoming sale info",
        "deal of the day",
        "special offer",
        "holiday sale?",
        "flash sale?",
        "discount percentage?",
        "coupon for this product",
        "can I get coupon",
        "show coupon codes",
        "apply discount",
        "discount for first order",
        "new user discount",
        "student discount",
        "bank offers",
        "credit card offer",
        "debit card offer",
        "cashback on UPI",
        "cashback on wallet",
        "offers on electronics",
        "offers on mobiles",
        "offers on clothes",
        "discount on shoes",
        "discount on bags",
        "sale on t-shirts",
        "buy 1 get 1",
        "BOGO offer",
        "half price sale",
        "clearance sale",
        "mega sale",
        "offer code please",
        "discount code please",
        "lowest price today",
        "is this product discounted",
        "product on sale?",
        "biggest discount?",
        "flash deal",
        "coupon valid?",
        "expired coupon",
        "coupon not working",
        "give me extra discount",
        "best coupon please",
        "50% off",
        "70% off",
        "flat discount",
        "discount for members",
        "reward points",
        "redeem reward points",
        "loyalty discount",
        "offer notification",
        "future discount",
        "lowest possible price",
        "price drop alert",
        "price drop?",
        "when is next sale",
        "black friday sale",
        "new year discount",
        "diwali sale",
        "christmas sale",
        "offer for today",
        "discount for bulk order",
        "bulk order discount",
        "combo offer",
        "bundle offer",
        "super saver offer",
        "apply promo",
        "promo code help",
        "extra discount for me",
        "cut price offer",
        "special price",
        "exclusive discount",
        "premium member offer",
        "VIP discount",
        "can I get price drop",
        "sale me kitna milega",
        "discount batao",
        "coupon dedo",
        "sale kab lagegi",
        "offer dikhaiye",
        "discount kaise milega",
        "any offer coupon"
      ],
      "responses": [
        "Here are the latest offers.",
        "Yes, we have several discounts available. What product are you interested in?",
        "You can find available coupons on the checkout page."
      ]
    },

    {
      "tag": "shipping_info",
      "patterns": [
        "what are shipping charges",
        "is shipping free",
        "delivery charge",
        "how much is shipping",
        "free delivery?",
        "shipping cost?",
        "delivery fees?",
        "fast delivery?",
        "express delivery?",
        "1 day delivery?",
        "same day delivery?",
        "delivery options?",
        "shipping methods?",
        "how long delivery takes",
        "delivery time?",
        "shipping time?",
        "expected delivery?",
        "is shipping delayed?",
        "why delivery slow?",
        "delivery schedule",
        "delivery timing",
        "delivery slot",
        "how to change delivery address",
        "address change?",
        "edit delivery address",
        "wrong address update",
        "delivery to my city?",
        "shipping availability?",
        "is delivery available here",
        "can you deliver to my area",
        "pin code delivery",
        "check pin code availability",
        "serviceable area?",
        "shipping outside city",
        "international shipping?",
        "global delivery?",
        "overseas delivery?",
        "delivery outside India?",
        "COD available?",
        "cash on delivery?",
        "is COD allowed",
        "COD charges?",
        "delivery restrictions",
        "delivery policy",
        "shipping terms",
        "delivery FAQ",
        "tracking after shipping",
        "after shipping how long",
        "shipping handling time",
        "packaging time",
        "when product shipped",
        "once shipped when delivered",
        "courier company?",
        "which courier service?",
        "who delivers package",
        "delivery partner?",
        "delivery boy contact",
        "can I schedule delivery",
        "can I choose delivery slot",
        "delivery preferences",
        "pickup option?",
        "store pickup?",
        "delivery speed?",
        "standard delivery?",
        "economy delivery?",
        "priority delivery?",
        "next day shipping",
        "weekend delivery",
        "holiday delivery",
        "delivery on Sunday?",
        "change delivery slot",
        "change delivery date",
        "delivery delayed",
        "why shipping slow",
        "package stuck",
        "when will you ship",
        "shipping availability check",
        "delivery region",
        "delivery zone",
        "delivery rules",
        "shipping insurance",
        "is parcel insured",
        "delivery safety",
        "contactless delivery",
        "doorstep delivery",
        "remote area delivery",
        "rural area shipping",
        "fastest delivery",
        "quickest shipping",
        "free shipping limit",
        "how to qualify free shipping",
        "shipping calculation",
        "shipping queries",
        "delivery related help",
        "delivery information request",
        "shipping help needed",
        "shipping clarification",
        "courier time estimate"
      ],
      "responses": [
        "Standard delivery is usually 2–5 days.",
        "Yes, free shipping is available on eligible items.",
        "Share your pin code to check delivery availability."
      ]
    },

    {
      "tag": "return_product",
      "patterns": [
        "I want to return my product",
        "return product",
        "how to return item",
        "return item please",
        "return request",
        "start return",
        "initiate return",
        "request return",
        "apply for return",
        "submit return request",
        "pickup return",
        "reverse pickup",
        "product return process",
        "how can I return",
        "I received damaged product",
        "damaged item return",
        "wrong product delivered",
        "wrong color delivered",
        "wrong size delivered",
        "return because damaged",
        "return reason defective",
        "received defective item",
        "item broken",
        "product broken",
        "product cracked",
        "product faulty",
        "item not working",
        "return not working product",
        "return policy apply",
        "return under warranty",
        "return period left",
        "can I still return",
        "return within 7 days?",
        "return window open?",
        "return eligibility check",
        "return pickup slot",
        "pickup schedule",
        "I want pickup time",
        "pickup delayed",
        "pickup not arrived",
        "pickup boy not coming",
        "return charges?",
        "return free?",
        "return shipping fee",
        "return label",
        "return label missing",
        "print return label",
        "no return label",
        "missing invoice return",
        "return without bill",
        "return without box?",
        "return packaging issue",
        "package for return instructions",
        "return packaging rules",
        "how to pack for return",
        "return conditions",
        "return requirements",
        "return approval",
        "return rejection reason",
        "return pending",
        "return accepted?",
        "return rejected?",
        "check return status",
        "status of my return",
        "refund after return",
        "refund after pickup",
        "refund time after return",
        "return tracking",
        "return shipment tracking",
        "reverse courier status",
        "return courier",
        "return department",
        "return support",
        "return help needed",
        "return problem",
        "product pickup problem",
        "I want to return fast",
        "urgent return",
        "return now",
        "return instructions please",
        "recollect item",
        "collect product back",
        "pickup request",
        "return item today",
        "pickup available today?",
        "pickup tomorrow",
        "pickup slot change",
        "change return time",
        "change pickup slot",
        "edit pickup information",
        "return details",
        "return troubleshooting",
        "return guidelines",
        "return ID required",
        "give my return ID",
        "return confirmation",
        "return generated?",
        "please help for return"
      ],
      "responses": [
        "Sure! I can help with returns. Please provide your order ID.",
        "Returns can be placed within 7 days of delivery.",
        "Your return request will be picked up once verified."
      ]
    },

    {
      "tag": "farewell",
      "patterns": [
        "bye",
        "goodbye",
        "see you",
        "see you later",
        "talk to you later",
        "thanks bye",
        "ok bye",
        "bye bot",
        "good night",
        "good day bye",
        "see ya",
        "later",
        "take care",
        "see you soon",
        "bye for now",
        "catch you later",
        "thank you bye",
        "I will go now",
        "ok see you",
        "bye assistant",
        "bye friend",
        "bye chatbot",
        "goodbye assistant",
        "see you next time",
        "I am done bye",
        "talk later",
        "finish the chat",
        "ending conversation",
        "close chat",
        "you can go now",
        "bye goodnight",
        "bye good afternoon",
        "bye good evening",
        "ending session",
        "end chat",
        "I am leaving",
        "bye take care",
        "thanks for help bye",
        "ok done bye",
        "closing now",
        "exit chat",
        "thank you next time",
        "ok I'm going",
        "see you later bot",
        "bye sweet bot",
        "bye service bot",
        "okay leaving",
        "done chatting bye",
        "conversation over",
        "I will come later",
        "bye helper",
        "thanks a lot bye",
        "thanks again bye",
        "bye dear bot",
        "okay bye now",
        "done bye",
        "I need to go bye",
        "I am going now",
        "signing off",
        "talk soon",
        "leave",
        "exit",
        "stop chat",
        "finish",
        "I'm done",
        "no more help bye",
        "thank you assistant",
        "that's all bye",
        "ok talk later",
        "I'll return later",
        "bye thank you",
        "thanks good bye",
        "good bye partner",
        "see you tomorrow",
        "meet later",
        "take care bye",
        "okay finishing",
        "conversation finish",
        "stop now",
        "close",
        "quit chat",
        "quit",
        "bye shop bot",
        "bye ecommerce bot",
        "done for today bye",
        "done for now bye",
        "alright bye",
        "that's it bye",
        "peace out",
        "peace bye",
        "see you soon bye",
        "later bye",
        "I will talk later"
      ],
      "responses": [
        "Goodbye! Have a great day!",
        "See you soon!",
        "Take care! Come back anytime."
      ]
    }
  ]
}
const normalized = text.toLowerCase().trim();

const botResponse = botResponse[normalizedText] || "Sorry, I don't understand that; "

const bot = await Bot.create({
  text: botResponse
})
return res.status(200).json({
   userMessage:user.text,
   botMessage:bot.text,
})
} catch (error){
    console.log("Error in message controller:",error);
    return res.status(500).json({error:"internal server Error"});
        }

    }
